# This workflow is designed for repositories that utilize GitHub issues.
#   It verifies that the pull request will close at least one issue upon merge, and
#   will fail if this is not the case.

name: Closes issue check
on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  closes-issue-check: 
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR closes an issue using GraphQL
        run: |
          REPO_OWNER=${{ github.event.repository.owner.login }}
          REPO_NAME=${{ github.event.repository.name }}
          PR_NUMBER=${{ github.event.pull_request.number }}

          QUERY=$(cat <<- EOM
          query(\$owner: String!, \$repo: String!, \$number: Int!) {
            repository(owner: \$owner, name: \$repo) {
              pullRequest(number: \$number) {
                closingIssuesReferences(last: 10) {
                  nodes {
                    number
                  }
                }
              }
            }
          }
          EOM
          )

          RESPONSE=$(gh api graphql -f query="$QUERY" -F owner=$REPO_OWNER -F repo=$REPO_NAME -F number=$PR_NUMBER)

          CLOSING_ISSUES=$(echo $RESPONSE | jq -r '.data.repository.pullRequest.closingIssuesReferences.nodes[] | .number')

          if [ -z "$CLOSING_ISSUES" ]; then
            echo "The pull request does not close any issue."
            exit 1
          else
            echo "The pull request closes the following issues: $CLOSING_ISSUES"
          fi
